<?php

/**
 * Implements hook_menu().
 */
function fatherhood_interactive_map_menu(){
  $items['interactive_map'] = array(
    'title' => 'Interactive Map',
    'page callback' => 'fatherhood_interactive_map_function',
    'access arguments' => array('access content'),
  );

  $items['interactive_map_details'] = array(
    'title' => 'Interactive Map Details',
    'page callback' => 'fatherhood_interactive_map_details_function',
    'access arguments' => array('access content'),
  );

  $items['interactive_map_js'] = array(
    'title' => 'Interactive Map Javascript',
    'page callback' => 'fatherhood_interactive_map_js_function',
    'access arguments' => array('access content'),
  );

  $items['interactive_map_print'] = array(
    'title' => 'Interactive Map Print All',
    'page callback' => 'fatherhood_interactive_map_print_function',
    'access arguments' => array('access content'),
  );

    return $items;
}

/*
 * Returns custom content to Drupal
 */

function fatherhood_interactive_map_function(){

  return theme('fatherhood_interactive_map_template');

}

function fatherhood_interactive_map_details_function(){

  return theme('fatherhood_interactive_map_details_template');

}

/*
 * add custom template for fatherhood program content type to be used with this module
 */

function fatherhood_interactive_map_preprocess_page(&$variables) {
  if (isset($variables['node']->type)) {
    $variables['theme_hook_suggestions'][] = 'page__' . $variables['node']->type;
  }
}


/**
 * Implements hook_theme().
 */
function fatherhood_interactive_map_theme(){

  $theme = array();

  $theme['page__fatherhood_program'] = array(
    'path' => drupal_get_path('module', 'fatherhood_interactive_map'),
    'template' => 'page--fatherhood-program',
    // template file name will be page--fatherhood-program.tpl.php
  );
  $theme['fatherhood_interactive_map_template'] = array(
    'path' => drupal_get_path('module', 'fatherhood_interactive_map'),
    'template' => 'fatherhood-interactive-map-page',
    // template file name will be fatherhood-interactive-map-page.tpl.php
  );
  $theme['fatherhood_interactive_map_details_template'] = array(
    'path' => drupal_get_path('module', 'fatherhood_interactive_map'),
    'template' => 'fatherhood-interactive-map-details-page',
    // template file name will be fatherhood-interactive-map-details-page.tpl.php
  );

  /*
  return array(
    'fatherhood_interactive_map_template' => array(
      // template file name will be fatherhood-interactive-map-page.tpl.php
      'template' => 'fatherhood-interactive-map-page',
    ),
    'fatherhood_interactive_map_details_template' => array(
      // template file name will be fatherhood-interactive-map-details-page.tpl.php
      'template' => 'fatherhood-interactive-map-details-page',
    ),
  );
  */

  return $theme;

}

function fatherhood_interactive_map_print_function(){

  $node_type = "fatherhood_programs "; // can find this on the node type's "edit" screen in the Drupal admin section.

  $nodes = db_query("SELECT nid FROM {node} WHERE status = 1 AND type = :type", array(':type' => $node_type))->fetchCol();

  $nodes = node_load_multiple($nodes);
  $x=1;

$output='
<script>
// self executing function here
(function() {

  function print(){
    window.print(); 
  }

})();
</script>
<button onclick="print()">Print</button>
';


  foreach ($nodes as $node) {


    $node = objectToArray($node);

    $nid=($node['nid']);

    $title = $node['title'];
    $address = $node['field_street_address']['und'][0]['value'];
    $city = $node['field_city']['und'][0]['value'];
    $state = $node['field_state']['und'][0]['value'];
    $zipcode = $node['field_zipcode']['und'][0]['value'];
    $phone = $node['field_phone']['und'][0]['value'];
    //$body = $node['body']['und'][0]['safe_value'];
    $url = url(drupal_get_path_alias('node/' . $node['nid']));




$output .= <<<EOHTML
<div class="row" >
<div id="" class="heading_3">
    <div id="" class="text " style="margin-bottom:15px;">
        <p><span style="color:#000000;font-weight:bold;">$x. </span><span style="color:#169BD5;font-weight:bold;">$title</span></p>
    </div>
</div>

<div id="" class="paragraph">
    <div id="" class="text ">
        <p><span>$address</span></p><p><span>$city, $state $zipcode</span></p><p><span>$phone</span></p>
    </div>
</div>
</div>
<hr>
EOHTML;
    $x++;
  }

  echo $output;

}

function fatherhood_interactive_map_js_function(){


}

/////////////////////////////////////////////////////////////////////////////




function objectToArray( $data ) {
    $d = "";

    if ( is_object( $data ) )

        $d = get_object_vars( $data );

    return $d;

}